# Site settings
title: 'Joy Mcleod' # Your Title
tagline: 'UI · UX Design, UI · UX Enthusiast, Front End Development, Consultant, Tech lover,  NASA Fan.' # A brief tagline for your site
sidebar_image: /images/full-pic.jpg

# Build settings
markdown: kramdown
highlighter: rouge
baseurl:  # the subpath of your site, e.g. /blog/
